"""
Transparency label engine (Milestone 5).

Maps an attribution verdict + confidence to one of THREE plain-language label variants. The label
is gated by confidence: a low-confidence AI/human *lean* collapses to the Uncertain label, so a
reader is never shown a confident accusation the system can't stand behind (false-positive aversion).
Variant text is verbatim from planning.md §3.
"""

from scoring import CONFIDENCE_GATE

# --- The three label variants (verbatim) ------------------------------------------------------

LABEL_AI = {
    "headline": "Likely AI-generated",
    "body": (
        "Our automated checks strongly indicate this text was generated by AI. Two independent "
        "checks — one that reads the writing's style and voice, and one that measures its "
        "structure and rhythm — both pointed the same way. This is a confident estimate, not "
        "proof. If you're the creator and you wrote this yourself, you can dispute it and a person "
        "will review it."
    ),
    "level": "High confidence",
}

LABEL_HUMAN = {
    "headline": "Likely human-written",
    "body": (
        "Our automated checks strongly indicate a person wrote this text. Both its voice and its "
        "structure look characteristic of human writing. This is a confident estimate, not a "
        "guarantee."
    ),
    "level": "High confidence",
}

LABEL_UNCERTAIN = {
    "headline": "Attribution uncertain",
    "body": (
        "We can't tell with confidence whether this text was written by a person or generated by "
        "AI — our checks either disagreed or landed in the middle. AI detection is imperfect, "
        "and formal, technical, or non-native-English writing is easy to misread as AI. We'd rather "
        "flag the uncertainty than guess. If you're the creator, you can add context through an "
        "appeal."
    ),
    "level": "Low confidence — inconclusive",
}


def label_for(attribution: str, confidence: float) -> dict:
    """Select the transparency label. Confidence gates the confident variants."""
    if attribution == "likely_ai" and confidence >= CONFIDENCE_GATE:
        variant = LABEL_AI
    elif attribution == "likely_human" and confidence >= CONFIDENCE_GATE:
        variant = LABEL_HUMAN
    else:
        # uncertain verdict, OR a verdict we're not confident enough to show
        variant = LABEL_UNCERTAIN
    return dict(variant)  # copy so callers can't mutate the templates


if __name__ == "__main__":
    print("AI, conf 0.85 ->", label_for("likely_ai", 0.85)["headline"])
    print("AI, conf 0.55 ->", label_for("likely_ai", 0.55)["headline"], "(collapses to uncertain)")
    print("HUMAN, conf 0.80 ->", label_for("likely_human", 0.80)["headline"])
    print("HUMAN, conf 0.55 ->", label_for("likely_human", 0.55)["headline"], "(collapses to uncertain)")
    print("UNCERTAIN ->", label_for("uncertain", 0.9)["headline"])
