"""
Detection signals for Provenance Guard.

Three genuinely distinct signals, each reading a different property of the text:

  Signal 1  llm_semantic_signal  — SEMANTIC: does it read with a human voice or a smooth, hedged,
            formal "AI register"? Uses Groq (llama-3.3-70b-versatile) when GROQ_API_KEY is set,
            otherwise a deterministic REGISTER heuristic (formality, hedging, connectors,
            contractions) so the system runs and tests without network.
  Signal 2  stylometry_signal    — STRUCTURAL: the statistical shape of the text (lives in
            stylometry.py: sentence-length variance, mean length, punctuation density).
  Signal 3  lexical_signal       — LEXICAL: surface fingerprints — AI cliché/buzzword phrases vs.
            casual human markers and slang. (Powers the Ensemble stretch feature.)

Signals 1 and 3 are kept deliberately different (voice/register vs. surface phrase lexicon) so the
ensemble is informative rather than three views of the same cue.
"""

import os
import re
import json

GROQ_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are an expert forensic linguist deciding whether a passage was written by a human or "
    "generated by an AI language model. Weigh voice consistency, concrete lived detail, idiosyncrasy "
    "and natural irregularity (signs of a human) against smooth, balanced, hedged, evenly-structured "
    "prose (signs of AI). Be cautious: formal, technical, or non-native-English human writing can "
    "look AI-like, so do not over-accuse. Respond with STRICT JSON only, no prose: "
    '{"ai_probability": <number between 0 and 1>, "rationale": "<one short sentence>"}'
)


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


# ============================================================================================
# Signal 1 — LLM semantic classifier (Groq, with offline register heuristic)
# ============================================================================================

def llm_semantic_signal(text: str) -> dict:
    """Return {'llm_score': float[0..1], 'rationale': str, 'source': str}."""
    api_key = os.environ.get("GROQ_API_KEY")
    if api_key:
        try:
            from groq import Groq

            client = Groq(api_key=api_key)
            resp = client.chat.completions.create(
                model=GROQ_MODEL,
                temperature=0,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": text},
                ],
            )
            data = json.loads(resp.choices[0].message.content)
            score = _clamp(float(data.get("ai_probability")))
            rationale = str(data.get("rationale", "")).strip()[:300]
            return {"llm_score": round(score, 3), "rationale": rationale, "source": "groq"}
        except Exception as exc:  # network down, bad key, parse error -> graceful fallback
            fb = _offline_register(text)
            fb["rationale"] = f"[offline fallback after {type(exc).__name__}] " + fb["rationale"]
            return fb
    return _offline_register(text)


_HEDGES = [
    "perhaps", "arguably", "it seems", "may", "might", "could", "tend to", "generally",
    "in general", "often", "typically", "it is possible", "to some extent", "relatively",
]
_CONNECTORS = [
    "furthermore", "moreover", "however", "additionally", "thus", "therefore", "consequently",
    "in conclusion", "as a result", "nevertheless", "firstly", "secondly",
]


def _offline_register(text: str) -> dict:
    """Deterministic register/voice heuristic standing in for the semantic LLM signal."""
    t = text.lower()
    words = re.findall(r"[a-zA-Z']+", t)
    n = max(len(words), 1)

    long_words = sum(1 for w in words if len(w) >= 8)
    formality = long_words / n
    contractions = len(re.findall(r"\b\w+'(t|s|re|ve|ll|d|m)\b", t))
    contraction_rate = contractions / n
    first_person_casual = 1 if re.search(r"\b(i|we|my|me|you)\b", t) and contraction_rate > 0 else 0
    hedges = sum(1 for h in _HEDGES if h in t)
    connectors = sum(1 for c in _CONNECTORS if c in t)

    score = 0.40
    score += min(max(formality - 0.10, 0.0) * 2.0, 0.30)   # formal register reads AI-ward
    score += min(connectors * 0.07, 0.18)                  # essay connectors read AI-ward
    score += min(hedges * 0.03, 0.10)                      # heavy hedging reads AI-ward
    score -= min(contraction_rate * 2.5, 0.22)             # contractions read human
    score -= 0.12 * first_person_casual                    # casual first person reads human
    if formality < 0.08:                                   # very plain, low-register voice
        score -= 0.08
    score = _clamp(score)

    rationale = (
        f"offline register heuristic: formality {formality:.2f}, {connectors} connector(s), "
        f"{hedges} hedge(s), contraction rate {contraction_rate:.2f}"
    )
    return {"llm_score": round(score, 3), "rationale": rationale, "source": "offline_fallback"}


# ============================================================================================
# Signal 3 — Lexical fingerprint (AI clichés/buzzwords vs. casual human markers)
# ============================================================================================

_AI_CLICHES = [
    "it is important to note", "it is worth noting", "it is equally", "paradigm", "stakeholders",
    "delve", "leverage", "navigate the complexities", "plays a crucial role", "in today's",
    "ever-evolving", "ever-changing", "multifaceted", "robust", "seamless", "underscore",
    "testament to", "transformative", "responsible deployment", "ethical implications",
    "various sectors", "collaborate to ensure", "innovative solutions", "sustainable growth",
    "strategic initiatives", "optimal outcomes", "operational efficiency", "digital landscape",
]
_CASUAL_MARKERS = [
    "lol", "honestly", "tbh", "kinda", "gonna", "wanna", "ngl", "ok so", "okay so", "i mean",
    "y'know", "you know", "way too", "probably won't", "drags me", "...", "?!", "ugh", "meh",
]


def lexical_signal(text: str) -> dict:
    """Return {'lexical_score': float[0..1], 'detail': {...}}. High = AI-like surface lexicon."""
    raw = text
    t = text.lower()
    words = re.findall(r"[a-zA-Z']+", t)
    n_sent = max(len(re.split(r"(?<=[.!?])\s+|\n+", text.strip())), 1)

    cliche_hits = sum(1 for c in _AI_CLICHES if c.lower() in t)
    casual_hits = sum(1 for c in _CASUAL_MARKERS if c.lower() in raw.lower())

    score = 0.50
    score += min(cliche_hits * 0.10, 0.40)
    score -= min(casual_hits * 0.10, 0.35)
    score = _clamp(score)

    return {
        "lexical_score": round(score, 3),
        "detail": {"ai_cliche_hits": cliche_hits, "casual_marker_hits": casual_hits,
                   "sentences": n_sent},
    }


if __name__ == "__main__":
    samples = {
        "clearly_ai": "Artificial intelligence represents a transformative paradigm shift in modern society. It is important to note that while the benefits of AI are numerous, it is equally essential to consider the ethical implications. Furthermore, stakeholders across various sectors must collaborate to ensure responsible deployment.",
        "clearly_human": "ok so i finally tried that new ramen place downtown and honestly? underwhelming. the broth was fine but they put WAY too much sodium in it and i was thirsty for like three hours after. my friend got the spicy version and said it was better. probably won't go back unless someone drags me there",
        "formal_human": "The relationship between monetary policy and asset price inflation has been extensively studied in the literature. Central banks face a fundamental tension between their mandate for price stability and the unintended consequences of prolonged low interest rates on equity and real estate valuations.",
        "edited_ai": "I've been thinking a lot about remote work lately. There are genuine tradeoffs - flexibility and no commute on one side, isolation and blurred work-life boundaries on the other. Studies show productivity varies widely by individual and role type.",
    }
    for name, txt in samples.items():
        print(f"{name:14s} sem={llm_semantic_signal(txt)['llm_score']:.2f}  lex={lexical_signal(txt)['lexical_score']:.2f}")
